#!/bin/bash
if [ ! -f /usr/local/lepuscp/logs/lepuscp.log ]; then
    echo "" > /usr/local/lepuscp/logs/lepuscp.log
fi
php5enmod ioncube
php5enmod zendguard
service php5-fpm restart
cd /usr/local/lepuscp/ && ./lepus > /usr/local/lepuscp/logs/console.log 2>&1 &
exit 0
