#!/bin/bash
openssl req -new -newkey rsa:2048 -days 9999 -nodes -x509 -subj /C=RU/ST=Moscow/L=Moscow/O=Lepus/CN=lepuscp -keyout /usr/local/lepuscp/ssl/server.key -out /usr/local/lepuscp/ssl/server.crt
if [ ! -f /usr/local/lepuscp/logs/lepuscp.log ]; then
    echo "" > /usr/local/lepuscp/logs/lepuscp.log
fi
cd /usr/local/lepuscp/ && ./lepus > /usr/local/lepuscp/logs/console.log 2>&1 &
